//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appbox.Reporting.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("appbox.Reporting.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ChartLayout_Error_PlotAreaWidthIs0 {
            get {
                return ResourceManager.GetString("ChartLayout_Error_PlotAreaWidthIs0", resourceCulture);
            }
        }
        
        internal static string ChartLayout_Error_PlotAreaHeightIs0 {
            get {
                return ResourceManager.GetString("ChartLayout_Error_PlotAreaHeightIs0", resourceCulture);
            }
        }
        
        internal static string DataSourceDefn_Error_NoPasswordForDSR {
            get {
                return ResourceManager.GetString("DataSourceDefn_Error_NoPasswordForDSR", resourceCulture);
            }
        }
        
        internal static string Filter_Error_TopNAndBottomNRequireInt {
            get {
                return ResourceManager.GetString("Filter_Error_TopNAndBottomNRequireInt", resourceCulture);
            }
        }
        
        internal static string Query_Error_XMLMustContainTopLevelRows {
            get {
                return ResourceManager.GetString("Query_Error_XMLMustContainTopLevelRows", resourceCulture);
            }
        }
        
        internal static string ReportLog_Error_Severity {
            get {
                return ResourceManager.GetString("ReportLog_Error_Severity", resourceCulture);
            }
        }
        
        internal static string Subreport_Error_SubreportNotParameter {
            get {
                return ResourceManager.GetString("Subreport_Error_SubreportNotParameter", resourceCulture);
            }
        }
        
        internal static string Table_Error_RecursiveGroupsMustOnlyGroupDefinition {
            get {
                return ResourceManager.GetString("Table_Error_RecursiveGroupsMustOnlyGroupDefinition", resourceCulture);
            }
        }
        
        internal static string TableRow_Error_TableRowNotRelatedToTable {
            get {
                return ResourceManager.GetString("TableRow_Error_TableRowNotRelatedToTable", resourceCulture);
            }
        }
        
        internal static string TableRows_Error_TableRowsMustOwnedTable {
            get {
                return ResourceManager.GetString("TableRows_Error_TableRowsMustOwnedTable", resourceCulture);
            }
        }
        
        internal static string CharReader_Error_FileReaderUnGetFirstChar {
            get {
                return ResourceManager.GetString("CharReader_Error_FileReaderUnGetFirstChar", resourceCulture);
            }
        }
        
        internal static string Financial_Error_IPmtNotSupportPayments {
            get {
                return ResourceManager.GetString("Financial_Error_IPmtNotSupportPayments", resourceCulture);
            }
        }
        
        internal static string FunctionCode_Error_MethodNotFound {
            get {
                return ResourceManager.GetString("FunctionCode_Error_MethodNotFound", resourceCulture);
            }
        }
        
        internal static string FunctionCustomInstance_Error_MethodNotFoundInClass {
            get {
                return ResourceManager.GetString("FunctionCustomInstance_Error_MethodNotFoundInClass", resourceCulture);
            }
        }
        
        internal static string FunctionCustomStatic_Error_MethodNotFoundInClass {
            get {
                return ResourceManager.GetString("FunctionCustomStatic_Error_MethodNotFoundInClass", resourceCulture);
            }
        }
        
        internal static string FunctionFieldCollection_Error_FieldCollectionNull {
            get {
                return ResourceManager.GetString("FunctionFieldCollection_Error_FieldCollectionNull", resourceCulture);
            }
        }
        
        internal static string FunctionFieldCollection_Error_FieldCollectionInvalid {
            get {
                return ResourceManager.GetString("FunctionFieldCollection_Error_FieldCollectionInvalid", resourceCulture);
            }
        }
        
        internal static string FunctionGlobalCollection_Error_GlobalsNull {
            get {
                return ResourceManager.GetString("FunctionGlobalCollection_Error_GlobalsNull", resourceCulture);
            }
        }
        
        internal static string FunctionGlobalCollection_Error_GlobalsUnknown {
            get {
                return ResourceManager.GetString("FunctionGlobalCollection_Error_GlobalsUnknown", resourceCulture);
            }
        }
        
        internal static string FunctionParameterCollection_Error_ParameterCollectionNull {
            get {
                return ResourceManager.GetString("FunctionParameterCollection_Error_ParameterCollectionNull", resourceCulture);
            }
        }
        
        internal static string FunctionParameterCollection_Error_ParameterCollectionInvalid {
            get {
                return ResourceManager.GetString("FunctionParameterCollection_Error_ParameterCollectionInvalid", resourceCulture);
            }
        }
        
        internal static string FunctionReportItemCollection_Error_ReportItemCollectionNull {
            get {
                return ResourceManager.GetString("FunctionReportItemCollection_Error_ReportItemCollectionNull", resourceCulture);
            }
        }
        
        internal static string FunctionReportItemCollection_Error_ReportItemCollectionInvalid {
            get {
                return ResourceManager.GetString("FunctionReportItemCollection_Error_ReportItemCollectionInvalid", resourceCulture);
            }
        }
        
        internal static string FunctionReportParameter_Error_UnknownReporParameterMethod {
            get {
                return ResourceManager.GetString("FunctionReportParameter_Error_UnknownReporParameterMethod", resourceCulture);
            }
        }
        
        internal static string FunctionSystem_Error_MethodNotFound {
            get {
                return ResourceManager.GetString("FunctionSystem_Error_MethodNotFound", resourceCulture);
            }
        }
        
        internal static string FunctionUserCollection_Error_UserCollectionNull {
            get {
                return ResourceManager.GetString("FunctionUserCollection_Error_UserCollectionNull", resourceCulture);
            }
        }
        
        internal static string FunctionUserCollection_Error_UserCollectionInvalid {
            get {
                return ResourceManager.GetString("FunctionUserCollection_Error_UserCollectionInvalid", resourceCulture);
            }
        }
        
        internal static string FunctionUserLanguage_Error_ConvertToDouble {
            get {
                return ResourceManager.GetString("FunctionUserLanguage_Error_ConvertToDouble", resourceCulture);
            }
        }
        
        internal static string FunctionUserLanguage_Error_ConvertToDecimal {
            get {
                return ResourceManager.GetString("FunctionUserLanguage_Error_ConvertToDecimal", resourceCulture);
            }
        }
        
        internal static string FunctionUserLanguage_Error_ConvertToInt32 {
            get {
                return ResourceManager.GetString("FunctionUserLanguage_Error_ConvertToInt32", resourceCulture);
            }
        }
        
        internal static string FunctionUserLanguage_Error_ConvertToDateTime {
            get {
                return ResourceManager.GetString("FunctionUserLanguage_Error_ConvertToDateTime", resourceCulture);
            }
        }
        
        internal static string FunctionUserLanguage_Error_ConvertToBoolean {
            get {
                return ResourceManager.GetString("FunctionUserLanguage_Error_ConvertToBoolean", resourceCulture);
            }
        }
        
        internal static string MhtBuilder_Error_FilenameNoExtension {
            get {
                return ResourceManager.GetString("MhtBuilder_Error_FilenameNoExtension", resourceCulture);
            }
        }
        
        internal static string MhtBuilder_Error_Extension {
            get {
                return ResourceManager.GetString("MhtBuilder_Error_Extension", resourceCulture);
            }
        }
        
        internal static string MhtWebFile_Error_ConvertOnlyHTMLOrCSS {
            get {
                return ResourceManager.GetString("MhtWebFile_Error_ConvertOnlyHTMLOrCSS", resourceCulture);
            }
        }
        
        internal static string MhtWebFile_Error_NoFilename {
            get {
                return ResourceManager.GetString("MhtWebFile_Error_NoFilename", resourceCulture);
            }
        }
        
        internal static string OneFileStreamGen_Error_FileAlreadyExists {
            get {
                return ResourceManager.GetString("OneFileStreamGen_Error_FileAlreadyExists", resourceCulture);
            }
        }
        
        internal static string PdfOutline_Error_GetObjectNumberMustBeforeGetOutlineDict {
            get {
                return ResourceManager.GetString("PdfOutline_Error_GetObjectNumberMustBeforeGetOutlineDict", resourceCulture);
            }
        }
        
        internal static string ProcessReport_Error_ReportHasErrors {
            get {
                return ResourceManager.GetString("ProcessReport_Error_ReportHasErrors", resourceCulture);
            }
        }
        
        internal static string Pages_Error_CurrentPageMustInList {
            get {
                return ResourceManager.GetString("Pages_Error_CurrentPageMustInList", resourceCulture);
            }
        }
        
        internal static string PageTextHtml_Error_BuildMethodMustCalledPriorTotalHeight {
            get {
                return ResourceManager.GetString("PageTextHtml_Error_BuildMethodMustCalledPriorTotalHeight", resourceCulture);
            }
        }
        
        internal static string RdlEngineConfig_Error_UnableCreateInstance {
            get {
                return ResourceManager.GetString("RdlEngineConfig_Error_UnableCreateInstance", resourceCulture);
            }
        }
        
        internal static string RdlEngineConfig_Error_NotKnownCustomReportItemType {
            get {
                return ResourceManager.GetString("RdlEngineConfig_Error_NotKnownCustomReportItemType", resourceCulture);
            }
        }
        
        internal static string RdlEngineConfig_Error_CashModuleNotFound {
            get {
                return ResourceManager.GetString("RdlEngineConfig_Error_CashModuleNotFound", resourceCulture);
            }
        }
        
        internal static string RdlEngineConfig_Error_CodeModuleNotLoaded {
            get {
                return ResourceManager.GetString("RdlEngineConfig_Error_CodeModuleNotLoaded", resourceCulture);
            }
        }
        
        internal static string MhtBuilder_Error_UnableDownload {
            get {
                return ResourceManager.GetString("MhtBuilder_Error_UnableDownload", resourceCulture);
            }
        }
        
        internal static string RDLParser_ErrorP__NoReport {
            get {
                return ResourceManager.GetString("RDLParser_ErrorP__NoReport", resourceCulture);
            }
        }
        
        internal static string RDLParser_ErrorP_XMLFailed {
            get {
                return ResourceManager.GetString("RDLParser_ErrorP_XMLFailed", resourceCulture);
            }
        }
        
        internal static string Lexer_ErrorP_InvalidNumberConstant {
            get {
                return ResourceManager.GetString("Lexer_ErrorP_InvalidNumberConstant", resourceCulture);
            }
        }
        
        internal static string Lexer_Error_SeparatorMustFollowedNumber {
            get {
                return ResourceManager.GetString("Lexer_Error_SeparatorMustFollowedNumber", resourceCulture);
            }
        }
        
        internal static string Lexer_ErrorP_UnterminatedString {
            get {
                return ResourceManager.GetString("Lexer_ErrorP_UnterminatedString", resourceCulture);
            }
        }
        
        internal static string Lexer_Error_UnterminatedComment {
            get {
                return ResourceManager.GetString("Lexer_Error_UnterminatedComment", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_AtColumn {
            get {
                return ResourceManager.GetString("Parser_ErrorP_AtColumn", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_EndExpressionExpected {
            get {
                return ResourceManager.GetString("Parser_ErrorP_EndExpressionExpected", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_AND_OR_RequiresBoolean {
            get {
                return ResourceManager.GetString("Parser_ErrorP_AND_OR_RequiresBoolean", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_NOTRequiresBoolean {
            get {
                return ResourceManager.GetString("Parser_ErrorP_NOTRequiresBoolean", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_MinusNeedNumbers {
            get {
                return ResourceManager.GetString("Parser_ErrorP_MinusNeedNumbers", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_FoundValue {
            get {
                return ResourceManager.GetString("Parser_ErrorP_FoundValue", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_BracketExpected {
            get {
                return ResourceManager.GetString("Parser_ErrorP_BracketExpected", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_IdentifierExpected {
            get {
                return ResourceManager.GetString("Parser_ErrorP_IdentifierExpected", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_FieldNotFound {
            get {
                return ResourceManager.GetString("Parser_ErrorP_FieldNotFound", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_FieldSupportsValueAndIsMissing {
            get {
                return ResourceManager.GetString("Parser_ErrorP_FieldSupportsValueAndIsMissing", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_ParameterNotFound {
            get {
                return ResourceManager.GetString("Parser_ErrorP_ParameterNotFound", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_ParameterSupportsValueAndLabel {
            get {
                return ResourceManager.GetString("Parser_ErrorP_ParameterSupportsValueAndLabel", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_ItemNotFound {
            get {
                return ResourceManager.GetString("Parser_ErrorP_ItemNotFound", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_ItemSupportsValue {
            get {
                return ResourceManager.GetString("Parser_ErrorP_ItemSupportsValue", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_GlobalsNotFound {
            get {
                return ResourceManager.GetString("Parser_ErrorP_GlobalsNotFound", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_UserVarNotFound {
            get {
                return ResourceManager.GetString("Parser_ErrorP_UserVarNotFound", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_UnknownIdentifer {
            get {
                return ResourceManager.GetString("Parser_ErrorP_UnknownIdentifer", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_AggregateCannotUsedWithinGrouping {
            get {
                return ResourceManager.GetString("Parser_ErrorP_AggregateCannotUsedWithinGrouping", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_AggregateCannotNestedInAnotherAggregate {
            get {
                return ResourceManager.GetString("Parser_ErrorP_AggregateCannotNestedInAnotherAggregate", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_Invalid_function_arguments {
            get {
                return ResourceManager.GetString("Parser_ErrorP_Invalid_function_arguments", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_ExpectingComma {
            get {
                return ResourceManager.GetString("Parser_ErrorP_ExpectingComma", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_iff_function_requires_3_arguments {
            get {
                return ResourceManager.GetString("Parser_ErrorP_iff_function_requires_3_arguments", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_ChooseRequires2Arguments {
            get {
                return ResourceManager.GetString("Parser_ErrorP_ChooseRequires2Arguments", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_ChooseFirstArgumentMustNumeric {
            get {
                return ResourceManager.GetString("Parser_ErrorP_ChooseFirstArgumentMustNumeric", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_SwitchRequires2Arguments {
            get {
                return ResourceManager.GetString("Parser_ErrorP_SwitchRequires2Arguments", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_SwitchMustEvenArguments {
            get {
                return ResourceManager.GetString("Parser_ErrorP_SwitchMustEvenArguments", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_SwitchMustBoolean {
            get {
                return ResourceManager.GetString("Parser_ErrorP_SwitchMustBoolean", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_FormatRequires2Arguments {
            get {
                return ResourceManager.GetString("Parser_ErrorP_FormatRequires2Arguments", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_SecondMustString {
            get {
                return ResourceManager.GetString("Parser_ErrorP_SecondMustString", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_FieldsRequires1Argument {
            get {
                return ResourceManager.GetString("Parser_ErrorP_FieldsRequires1Argument", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_UnknownProperty {
            get {
                return ResourceManager.GetString("Parser_ErrorP_UnknownProperty", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_ParametersRequires1Argument {
            get {
                return ResourceManager.GetString("Parser_ErrorP_ParametersRequires1Argument", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_ReportItemsRequires1Argument {
            get {
                return ResourceManager.GetString("Parser_ErrorP_ReportItemsRequires1Argument", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_GlobalsRequires1Argument {
            get {
                return ResourceManager.GetString("Parser_ErrorP_GlobalsRequires1Argument", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_UserRequires1Argument {
            get {
                return ResourceManager.GetString("Parser_ErrorP_UserRequires1Argument", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_RunningValue_takes_2_or_3_arguments {
            get {
                return ResourceManager.GetString("Parser_ErrorP_RunningValue_takes_2_or_3_arguments", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_RunningValueArgumentInvalid {
            get {
                return ResourceManager.GetString("Parser_ErrorP_RunningValueArgumentInvalid", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_RunningValueNotSupported {
            get {
                return ResourceManager.GetString("Parser_ErrorP_RunningValueNotSupported", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_ScopeMustConstant {
            get {
                return ResourceManager.GetString("Parser_ErrorP_ScopeMustConstant", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_ScopeNotKnownDataSet {
            get {
                return ResourceManager.GetString("Parser_ErrorP_ScopeNotKnownDataSet", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_NoScope4Aggregate {
            get {
                return ResourceManager.GetString("Parser_ErrorP_NoScope4Aggregate", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_FieldNotInDataSet {
            get {
                return ResourceManager.GetString("Parser_ErrorP_FieldNotInDataSet", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_AggregateMust1Argument {
            get {
                return ResourceManager.GetString("Parser_ErrorP_AggregateMust1Argument", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_ScopeNotSpecifiedInHeaderOrFooter {
            get {
                return ResourceManager.GetString("Parser_ErrorP_ScopeNotSpecifiedInHeaderOrFooter", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_ScopeNotKnownGrouping {
            get {
                return ResourceManager.GetString("Parser_ErrorP_ScopeNotKnownGrouping", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_ScopeIdentifer {
            get {
                return ResourceManager.GetString("Parser_ErrorP_ScopeIdentifer", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_NotCodeMethod {
            get {
                return ResourceManager.GetString("Parser_ErrorP_NotCodeMethod", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_FunctionUnknown {
            get {
                return ResourceManager.GetString("Parser_ErrorP_FunctionUnknown", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_ClassUnknown {
            get {
                return ResourceManager.GetString("Parser_ErrorP_ClassUnknown", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_FunctionOfClassUnknown {
            get {
                return ResourceManager.GetString("Parser_ErrorP_FunctionOfClassUnknown", resourceCulture);
            }
        }
        
        internal static string Parser_ErrorP_CurlyBracketExpected {
            get {
                return ResourceManager.GetString("Parser_ErrorP_CurlyBracketExpected", resourceCulture);
            }
        }
    }
}
