name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Setup NetCoreBeauty
      run: dotnet tool install --global nulastudio.ncbeauty
    - name: Build with dotnet
      run: |
        dotnet publish -r win-x64 -c Release -o bin\AppContainer appbox.AppContainer\appbox.AppContainer.csproj
        ncbeauty --loglevel=Info --nopatch=True bin\AppContainer lib
        dir bin\AppContainer
        dotnet publish -r win-x64 -c Release -o bin\Host appbox.Host\appbox.Host.csproj
        ncbeauty --loglevel=Info --nopatch=True bin\Host lib
        dir bin\Host
    - name: Push to deploy repo
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global core.autocrlf input
        git clone https://.:${{ secrets.GITHUB_TOKEN }}@github.com/enjoycode/appbox.deploy.win bin\deploy
        #rm bin\deploy\lib -Force -Recurse
        #xcopy /E /I /Y /Q "bin\AppContainer" "bin\deploy"
        #xcopy /E /I /Y /Q "bin\Host" "bin\deploy"
        #xcopy /I /Y /Q "build\debugger\netcoredbg.exe" "bin\deploy\lib"
        #xcopy /I /Y /Q "build\debugger\SymbolReader.dll" "bin\deploy\lib"
        #dir bin\deploy\lib\netcore*
        #dir bin\deploy\lib\SymbolReader*
        xcopy /I /Y /Q "bin\Host\appbox.Host.dll" "bin\deploy"
        
        cd bin\deploy
        echo "====git add===="
        git add -A
        git status
        echo "====git commit===="
        git config user.email "enjoycode@icloud.com"
        git config user.name "$GITHUB_ACTOR"
        git commit -m "CI by appbox.clr"
        echo "====git push==="
        #echo toJson(github.event.commits)
        #echo toJson(github.event)
        git push
