name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Setup NetCoreBeauty
      run: dotnet tool install --global nulastudio.ncbeauty
    - name: Build with dotnet
      run: |
        dotnet publish -r win-x64 -c Release -o bin\AppContainer appbox.AppContainer\appbox.AppContainer.csproj
        ncbeauty --loglevel=Info --nopatch=True bin\AppContainer lib
        dir bin\AppContainer
        dotnet publish -r win-x64 -c Release -o bin\Host appbox.Host\appbox.Host.csproj
        ncbeauty --loglevel=Info --nopatch=True bin\Host lib
        dir bin\Host
    - name: Push to deploy repo
      run: |
        git clone https://.:${{ secrets.GITHUB_TOKEN }}@github.com/enjoycode/appbox.deploy.win bin\deploy
        rm bin\deploy\lib -Force -Recurse
        xcopy /E /I /Y /Q "bin\AppContainer" "deploy"
        xcopy /E /I /Y /Q "bin\Host" "deploy"
        xcopy /I /Y /Q "build\debugger\netcoredbg.exe" "deploy\lib"
        xcopy /I /Y /Q "build\debugger\SymbolReader.dll" "deploy\lib"
        #dir deploy\lib\netcore*
        #dir deploy\lib\SymbolReader*
        
        cd deploy
        echo "====git add===="
        git config --global core.autocrlf false
        git add -A .
        git status
        dir
        echo "====git commit===="
        #git commit -m "CI by appbox.clr"
        #git status
        echo "====git done==="
        #echo toJson(github.event.commits)
        #echo toJson(github.event)
        #git push
